### ISSUE TITLE
Connect to server

### ISSUE THREAD

**Issue by dmitrylc** [Ochii/cso2-master-server#1]
How to connect to the server?

**Comment by Ochii** [comment]
You can use [this client](https://github.com/Ochii/cso2-launcher/tree/server_emulator). It will connect by default to the TCP port 30001.

If you wish to use some other port you would have to [change this line](https://github.com/Ochii/cso2-launcher/blob/f45a17244839775c713bacbe1b715dccb46ef183/src/launcher/hooks/engine.cpp#L34) in the client and [this line](https://github.com/Ochii/cso2-master-server/blob/844d2d69bd60876ddc8c957ee9093b39d90d91ab/src/server.ts#L7) in the server to the port number you desire.

**Comment by dmitrylc** [comment]
[Are these settings already in the release? ](https://github.com/Ochii/cso2-launcher/blob/f45a17244839775c713bacbe1b715dccb46ef183/src/launcher/hooks/engine.cpp#L34)

The console does not write anything when connected.
[This is how it happens.](https://drive.google.com/file/d/1Ze_bagYj8HOTaRgx6J3Mfurd7aAUignx/view)

**Comment by Ochii** [comment]
No, that's not in the master branch

**Comment by dmitrylc** [comment]
![error](https://user-images.githubusercontent.com/2939460/45378807-1e0d1400-b607-11e8-894e-eae96fcc89fe.JPG)
I can not install ["source-sdk-cso2"](https://github.com/Ochii/source-sdk-cso2)

**Comment by Ochii** [comment]
You probably didn't clone the submodules, try cloning with ```git clone --recursive https://github.com/Ochii/cso2-launcher.git -b server_emulator```

**Comment by Ochii** [comment]
it should work now, give it a try

**Comment by dmitrylc** [comment]
![cmd](https://user-images.githubusercontent.com/2939460/45382143-0e45fd80-b610-11e8-8e68-17a0462d5961.png)
Everything is working
