### ISSUE TITLE
other servers have completed their own features! and they don't share! why don't you still develop this server?

### ISSUE THREAD

**Issue by IGNRexI** [Ochii/cso2-master-server#139]
other servers have completed their own features! and they don't share! why don't you still develop this server?
------------
> Shop
> Friend
> Clan
> Customize
> Ranking
> weapon sorting
> Megaphone
> Sending Gifts
> USER INFO
------------------
V.S V.S V.S

Sample Video: https://www.youtube.com/watch?v=a6451UibuUs

**Comment by LostXboy** [comment]
actually this server emulator should be under GPL3 licanse

**Comment by IGNRexI** [comment]
> actually this server emulator should be under GPL3 licanse

server should be improved. and why do other servers think of themselves?

**Comment by JusicP** [comment]
> > actually this server emulator should be under GPL3 licanse
> 
> server should be improved. and why do other servers think of themselves?

as i know L-Leite working on holepunch

**Comment by IGNRexI** [comment]
how long can this take?

**Comment by organnerx** [comment]
You got a basic server. Now go and improve it by yourself. Noone will share code of the new features for free after spending hundreds of hours for it to work.
