### ISSUE TITLE
I create a game ,But other player can not join the game

### ISSUE THREAD

**Issue by ChenyuHou** [Ochii/cso2-master-server#18]
I create a game ,But other player can not join the game
@DebugBios @Ochii 
If you can solve the problem , Please tell me , thanks
![1](https://user-images.githubusercontent.com/45506338/50545363-8cc0bc80-0c4c-11e9-9628-1953fe8868d6.png)

**Comment by DebugBios** [comment]
If a host enters a game slowly, an error code is loaded (because the person entering the game starts loading after the host enters the game).

**Comment by Ochii** [comment]
@ChenyuHou is this a NAT issue or are you unable to join ongoing matches?

**Comment by Chinayangzhihong** [comment]
> @ChenyuHou你的NAT开放吗? 或者你无法加入正在进行的比赛吗?

Sorry, I just saw. NAT is fixed. Similar to creating a small LAN. The local host serves as the server. No other modes except Biochemical Z can be played. Other players entering the game are similar to the observer mode. Other players can not join the camp, can you solve this problem?

**Comment by Ochii** [comment]
> 
> 
> > @ChenyuHou你的NAT开放吗? 或者你无法加入正在进行的比赛吗?
> 
> Sorry, I just saw. NAT is fixed. Similar to creating a small LAN. The local host serves as the server. No other modes except Biochemical Z can be played. Other players entering the game are similar to the observer mode. Other players can not join the camp, can you solve this problem?

I can't reproduce your issues, are you running the [latest release](https://github.com/Ochii/cso2-master-server/releases/tag/20190112025631-93d84af)?

**Comment by Chinayangzhihong** [comment]
> > > @ChenyuHou你的NAT开放吗? 或者你无法加入正在进行的比赛吗?
> > 
> > 
> > 对不起,我刚刚看到。 NAT是固定的。 类似于创建一个小型局域网。 本地主机作为服务器。 没有其他模式除了可以玩生化Z。 其他玩家进入游戏类似于观察者模式。 其他球员不能参加夏令营,你能解决这个问题吗?
> 
> 我不能复制你的问题,你运行[最新版本](https://github.com/Ochii/cso2-master-server/releases/tag/20190112025631-93d84af)吗?

Yes, but somebody seems to have fixed it. I'll try it now.

**Comment by Chinayangzhihong** [comment]
Now we can play, it is estimated that it is compulsory to help players choose camps.

**Comment by Ochii** [comment]
@Chinayangzhihong create a [new issue](https://github.com/Ochii/cso2-master-server/issues/new) with your problem, since this one is not related to yours
