### ISSUE TITLE
Server execution error occurs when using externalip.

### ISSUE THREAD

**Issue by DebugBios** [Ochii/cso2-master-server#19]
Error: Room: host's countdown does not match ours
    at Room.progressCountdown (C:\Users\rat96\dist\room\room.js:323:19)
    at ChannelManager.onGameStartToggleRequest (C:\Users\rat96\dist\channel\channelmanager.js:340:29)
    at ChannelManager.onRoomRequest (C:\Users\rat96\dist\channel\channelmanager.js:70:25)
    at ServerInstance.onIncomingPacket (C:\Users\rat96\dist\serverinstance.js:200:38)
    at ServerInstance.processPackets (C:\Users\rat96\dist\serverinstance.js:169:18)
    at ServerInstance.onSocketData (C:\Users\rat96\dist\serverinstance.js:160:14)
    at Socket.newSocket.on (C:\Users\rat96\dist\serverinstance.js:85:18)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)

**Comment by Ochii** [comment]
Which game mode did you try?

**Comment by DebugBios** [comment]
<iframe width="560" height="315" src="https://www.youtube.com/embed/3_QVBZ9UoYo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> zombie Z

**Comment by DebugBios** [comment]
https://youtu.be/3_QVBZ9UoYo
Zombie Z mode

Also, it is impossible to start a game while the person entering the room is ready.

**Comment by DebugBios** [comment]
There are errors in all game modes.

**Comment by Ochii** [comment]
Can you do that again with the latest version and upload both the server log and packets?

**Comment by DebugBios** [comment]
Your environment has been set up for using Node.js 8.11.4 (x64) and npm.

C:\Users\rat96>npm install --only=production
removed 389 packages in 3.932s

C:\Users\rat96>npm run start -- --ip-address [my router external IP address]

> cso2-master-server@0.3.0 start C:\Users\rat96
> node dist/server.js "--ip-address" "[my router external IP address]"

server error: bind EADDRNOTAVAIL [my router external IP address]:30002
C:\Users\rat96\dist\serverinstance.js:112
        throw err;
        ^

Error: bind EADDRNOTAVAIL[my router external IP address]:30002
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at _handle.lookup (dgram.js:266:18)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cso2-master-server@0.3.0 start: `node dist/server.js "--ip-address" "[my router external IP address]"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cso2-master-server@0.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rat96\AppData\Roaming\npm-cache\_logs\2019-01-06T17_53_51_483Z-debug.log

**Comment by DebugBios** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--ip-address',
1 verbose cli   '[my router external IP address]' ]
2 info using npm@5.6.0
3 info using node@v8.11.4
4 verbose config Skipping project config: C:\Users\rat96/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle cso2-master-server@0.3.0~prestart: cso2-master-server@0.3.0
7 info lifecycle cso2-master-server@0.3.0~start: cso2-master-server@0.3.0
8 verbose lifecycle cso2-master-server@0.3.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle cso2-master-server@0.3.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\rat96\node_modules\.bin;C:\Users\rat96\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\OpenVPN\bin;C:\Program Files\nodejs\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Users\rat96\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip\;C:\Users\rat96\AppData\Roaming\npm;;D:\Steam\steamapps\common\counter-strike source\cstrike\..\bin
10 verbose lifecycle cso2-master-server@0.3.0~start: CWD: C:\Users\rat96
11 silly lifecycle cso2-master-server@0.3.0~start: Args: [ '/d /s /c',
11 silly lifecycle   'node dist/server.js "--ip-address" "[my router external IP address]"' ]
12 silly lifecycle cso2-master-server@0.3.0~start: Returned: code: 1  signal: null
13 info lifecycle cso2-master-server@0.3.0~start: Failed to exec start script
14 verbose stack Error: cso2-master-server@0.3.0 start: `node dist/server.js "--ip-address" "[my router external IP address]"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid cso2-master-server@0.3.0
16 verbose cwd C:\Users\rat96
17 verbose Windows_NT 10.0.17763
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start" "--" "--ip-address" "[my router external IP address]"
19 verbose node v8.11.4
20 verbose npm  v5.6.0
21 error code ELIFECYCLE
22 error errno 1
23 error cso2-master-server@0.3.0 start: `node dist/server.js "--ip-address" "[my router external IP address]"`
23 error Exit status 1
24 error Failed at the cso2-master-server@0.3.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by Ochii** [comment]
Looks like I commented the wrong issue, I meant to send that to #20.

You need to host the server in your machine and port forward the router. Try removing the `--ip-address` parameter

**Comment by DebugBios** [comment]
My router must be out of order. Even though port forwarding is set, the port won't open. This seems to be a problem with my router.
