### ISSUE TITLE
cannot open include file 'afxres.h'.

### ISSUE THREAD

**Issue by dmitrylc** [Ochii/cso2-master-server#2]
cannot open include file 'afxres.h'.
![errovc](https://user-images.githubusercontent.com/2939460/45449061-d1940800-b6dc-11e8-86b6-deee2f4f1a81.JPG)

Log build:

```
1>------ Build started: Project: capstone-static, Configuration: Debug Win32 ------
1>Error: The operation could not be completed 
2>------ Build started: Project: PolyHook_2, Configuration: Debug Win32 ------
2>Error: The operation could not be completed 
3>------ Build started: Project: launcher_main, Configuration: Debug Win32 ------
3>git : The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the s
3>pelling of the name, or if a path was included, verify that the path is correct and try again.
3>At T:\cso2-launcher-server_emulator\gengithash.ps1:1 char:9
3>+ $hash = git log --pretty=format:'%h' -n 1
3>+         ~~~
3>    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
3>    + FullyQualifiedErrorId : CommandNotFoundException
3>
3>current git commit hash is
3>main.cpp
3>launcher_main.rc(10): fatal error RC1015: cannot open include file 'afxres.h'.
3>
3>Done building project "launcher_main.vcxproj" -- FAILED.
========== Build: 0 succeeded, 3 failed, 6 up-to-date, 0 skipped ==========
```

**Comment by Ochii** [comment]
try it again, and next time [open an issue in the client project repository](https://github.com/Ochii/cso2-launcher/issues)

**Comment by dmitrylc** [comment]
![cso2error](https://user-images.githubusercontent.com/2939460/45479914-697f0980-b750-11e8-94c5-faf103c77cba.png)
Happened!
In the sources, I specify my local server. But nothing happened.

**Comment by Ochii** [comment]
did you change the IP here [here](https://github.com/Ochii/cso2-launcher/blob/ec8f95c11b556010814afe90b9ff5b2cd549665b/src/launcher/hooks/engine.cpp#L25)?

**Comment by dmitrylc** [comment]
Yes. 
![ipconfig](https://user-images.githubusercontent.com/2939460/45511812-ae358f80-b7a6-11e8-9c95-780bddbc6dac.JPG)

**Comment by Ochii** [comment]
Could you try cloning the server_emulator branch again? You are missing some engine patches

**Comment by dmitrylc** [comment]
Downloaded again "Server". Nothing has changed.

**Comment by Ochii** [comment]
is the code in src/hooks/engine.cpp still the same?

**Comment by dmitrylc** [comment]
Yes

**Comment by Ochii** [comment]
there's something wrong then, because the code [looks like this](https://github.com/Ochii/cso2-launcher/blob/server_emulator/src/launcher/hooks/engine.cpp) in the latest commit

**Comment by dmitrylc** [comment]
Downloaded again "cso2-launcher". Anyway, the game can not connect to the server.

**Comment by dmitrylc** [comment]
After updating the repository. I was able to connect to the server.

**Comment by Ochii** [comment]
Good to hear that. I'm closing this issue
