### ISSUE TITLE
Host cannot change team in room.

### ISSUE THREAD

**Issue by DebugBios** [Ochii/cso2-master-server#22]
![default](https://user-images.githubusercontent.com/44349391/50854709-26b10380-13c9-11e9-9714-88f413f22ed4.PNG)

user "TEST" tried change team in a room, although it's ready. room name "명작의 부활! 카운터스트라이크 온라인2" room id: 2

**Comment by Ochii** [comment]
This was fixed in [commit b117137](https://github.com/Ochii/cso2-master-server/commit/b117137fcd47639be7b5586e64cabb97b3d45dc6)
