### ISSUE TITLE
The game is in low violence mode only

### ISSUE THREAD

**Issue by DebugBios** [Ochii/cso2-master-server#25]
It is now operating in a teenage version.

The teenage version has no blood-related effects.

**Comment by Ochii** [comment]
Try the [latest build of cso2-launcher](https://github.com/Ochii/cso2-launcher/releases/tag/Build-0.1.13). The adult features are now enabled by default.

You can still control the adult features with the ```cso2_teen``` console variable (setting it to `1` disables blood).
