### ISSUE TITLE
Some game modes are not available

### ISSUE THREAD

**Issue by w123456w30w** [Ochii/cso2-master-server#31]
gz
gz_intro
gz_tour
gz_pve
madcity
zd_boss1
zd_boss2
zd_boss3

not on the list cannot be selected

**Comment by DebugBios** [comment]
gz 
gz_intro 
gz_tour
Both modes were used in the test version and the file was deleted after the official service.

zd_boss1 
zd_boss2 
zd_boss3

The mode shall be able to start from "보스일일미션".
gz_pve mode should be marked at the top of the quick start and also server and character creation for that mode.

Also, other modes are removed after the UI renewal patch, so you cannot create a room normally.

**Comment by DebugBios** [comment]
Missing mode after the UI renewal patch. or test mode,

GUNTEAMDEATH (The currently displayed mode is the "re" Version)

PIG
ANIMATIONTEST_VCD
GZ_SURVIVOR
DEVTEST
SCENARIO_TEST
GZ
GZ_TOUR
EVENTMOD01
DUEL
GZ_ZB
HEROES
EVENTMOD02
ZOMBIECRAFT
CAMPAIGN5
CAMPAIGN6
CAMPAIGN7
CAMPAIGN8
CAMPAIGN9
GHOST
HIDE_MATCH
HIDE_ICE
DIY
HIDE_ITEM
ZOMBIE_COMMANDER
CASUALORIGINAL
GUNBALL
TDM_SMALL
DE_SMALL
HIDE_MULTI

**Comment by Gazyi** [comment]
I don't see it in quick start on my client.
![cso2_0000_1](https://user-images.githubusercontent.com/10533703/52656872-555e5480-2f08-11e9-9396-88316fc9e03a.jpg)

**Comment by DebugBios** [comment]
@Gazyi 
The mode at the top is changeable on the server.

However, the function does not yet exist.

**Comment by organnerx** [comment]
It will be great to add all remaining game modes to the mode choosing window. We will wait for it

**Comment by Ochii** [comment]
I'm closing this in favor of #45 since it's related to this issue and has more info about it
