### ISSUE TITLE
When a match ends, you can only join it

### ISSUE THREAD

**Issue by DebugBios** [Ochii/cso2-master-server#32]
Only the entry button is activated. At the end of the competition it must be the ready button, not the input button.

**Comment by Ochii** [comment]
I can't reproduce this. Did I misunderstand the issue?

**Comment by DebugBios** [comment]
This was solved in the latest version.

**Comment by DebugBios** [comment]
Users who enter the game using the game entry button have only the input button, not the preparation button after the game ends.
