### ISSUE TITLE
Error 12002 has occurred

### ISSUE THREAD

**Issue by kr1staa** [Ochii/cso2-master-server#33]
![p8ldsl 65 w 7uv25a n b](https://user-images.githubusercontent.com/47288667/52172536-40691f00-27ac-11e9-8149-3f43f90afc54.png)
 i cant start the game, how to set the server sv_cheat 1?

**Comment by GEEKiDoS** [comment]
https://github.com/Ochii/cso2-launcher/issues/20#issue-405969049

Maybe a similar issue

**Comment by Ochii** [comment]
Duplicate of Ochii/cso2-launcher#20
