### ISSUE TITLE
after several matches, disconnected from the server, unavoidable

### ISSUE THREAD

**Issue by lisigang1994** [Ochii/cso2-master-server#36]
If anyone knows about how to solve it. Thanks a lot
![wb 6h3ol8guqp 6 x3o c](https://user-images.githubusercontent.com/47348186/52261496-8f59b480-2964-11e9-8e4f-f177df99dd97.jpg)

**Comment by leang97** [comment]
Why is my name on my own server lel. I never play the game for 2 days. Btw, from the npm logs, it shows that sometimes client request non existent users or room trigger a server side crash, will see if I can loop the server scripts

**Comment by lisigang1994** [comment]
> Why is my name on my own server and other people's server lel. I never play the game for 2 days. Btw, from the npm logs, it shows that sometimes client request non existent users or room trigger a server side crash, will see if I can loop the server scripts.
> 
> In your case, looks like your client have disconnected or crashed in some case.

**Comment by lisigang1994** [comment]
![8tk3u6k7173p2zwtp9gzye](https://user-images.githubusercontent.com/47348186/52276045-1c643400-298c-11e9-9b39-b32a9654d660.png)

**Comment by Ochii** [comment]
are these 2 different issues @lisigang1994 ?

**Comment by leang97** [comment]
> are these 2 different issues @lisigang1994 ?

I think its the same issue. His server detected that the client get the socket closed, and his client display that error 12002 has occured.

**Comment by Ochii** [comment]
Duplicate of Ochii/cso2-launcher#20
