### ISSUE TITLE
Item for ZOMBIE CRUSH not available.

### ISSUE THREAD

**Issue by leang97** [Ochii/cso2-master-server#38]
The items that were able to use in the game mode of zombie crush is not available in example, healing item and protective item.
And how do we find the item code that we can push in user inventory?

**Comment by Ochii** [comment]
When you extract the games files, you can find item codes in `scripts/cso2_item_rev2.csv`.

I think the zombie crush items are between ids 2019 and 2028. I'll add them to the temporary inventory

**Comment by Ochii** [comment]
I added the items to the latest build

**Comment by leang97** [comment]
Thanks @Ochii
