### ISSUE TITLE
Server disconnect when adding bots

### ISSUE THREAD

**Issue by lisigang1994** [Ochii/cso2-master-server#40]
Apologize for asking the same question again. I just play offline server, but always get disconnect from the server due to adding bots or start a room, just like the pictures. I dont know why it shut down and shows me that. (updated 0.2.2 Launcher and new server). If anyone knows about this or meet the same problem, thanks for sharing

**Comment by lisigang1994** [comment]
![aa](https://user-images.githubusercontent.com/47348186/52529523-8df60680-2d2d-11e9-9291-4072fc041ad2.png)

**Comment by lisigang1994** [comment]
![as](https://user-images.githubusercontent.com/47348186/52529525-99493200-2d2d-11e9-8ada-7ef7d3a8ce48.jpg)

**Comment by Ochii** [comment]
I think I managed to reproduce this.

If you set max players to 32, add the max ammount of bots, then set max players to less than 32, the bot number will remain the same. If you start the match with the bugged bot count you get disconnected

**Comment by lisigang1994** [comment]
Thats it. Hope this would be fixed later, thanks

**Comment by Ochii** [comment]
I pushed a fix. If this is still broken I'll reopen the issue

**Comment by lisigang1994** [comment]
thanks

**Comment by lisigang1994** [comment]
> I pushed a fix. If this is still broken I'll reopen the issue

I think that problem is still exist. I started 5 rooms with same 32 bots also cause game disconnect from the server, have updated server and launcher to the newest, looks like still have this problem, hope we could fix that, thanks
![6 6m_qtz lnk3p4 xei 4b](https://user-images.githubusercontent.com/47348186/52562002-08ab4880-2e38-11e9-9e40-9194c667f4fd.png)
![mp vhfy ublawahnr709g3m](https://user-images.githubusercontent.com/47348186/52562006-0e089300-2e38-11e9-9d8f-4b691db89f5d.png)

**Comment by lisigang1994** [comment]
I ll upload a video of youtube later today to explain how it happens more clarify

**Comment by lisigang1994** [comment]
https://youtu.be/aPjcZFtL0Z8

**Comment by Ochii** [comment]
*Originally posted by [lisigang1994](/lisigang1994), #44 *

> 
> 
> sorry for disturbing. I tried the new server yesterday and found the problem of issue40 still exist.I have uploaded a video to explain how it happens.tThe link is here. Thanks again. https://youtu.be/aPjcZFtL0Z8

**Comment by Ochii** [comment]
When you update some room setting, the master server does a full settings update for everyone in the room. You can notice the game is slow when you add many bots at once.

**Comment by lisigang1994** [comment]
> When you update some room setting, the master server does a full settings update for everyone in the room. You can notice the game is slow when you add many bots at once.

a slight loss of frame rates maybe, dont know if that full setting update cause the disconnection
