### ISSUE TITLE
launcher_main.exe is not opening the game

### ISSUE THREAD

**Issue by Ardibengu** [Ochii/cso2-master-server#48]
i open launcher main and the game doesn't open
what's wrong?
i installed visualc  by the way

**Comment by Ochii** [comment]
you're using an old version of the launcher. go to https://github.com/Ochii/cso2-launcher to get the newest version.

also you should have opened this issue in there

**Comment by Ardibengu** [comment]
> you're using an old version of the launcher. go to https://github.com/Ochii/cso2-launcher to get the newest version.
> 
> also you should have opened this issue in there

Hello i fixed the launcher but now how do i type joinroom or jointeam or to get the weapons i don't have anything to type-in to control the game
