### ISSUE TITLE
Room match error

### ISSUE THREAD

**Issue by Bridium** [Ochii/cso2-master-server#49]
it's well work until get two players in one room(I'm using laptop, and desktop)
and single play run well like classic mission, teamdeath mode, e.t.c...
but two player in one room game crash...
how can i fix this error?

![image](https://user-images.githubusercontent.com/43029852/53003129-a07ce800-3471-11e9-8a97-22dc0368f93b.png)

![image](https://user-images.githubusercontent.com/43029852/53003341-1719e580-3472-11e9-99cd-559573e2d26c.png)

![image](https://user-images.githubusercontent.com/43029852/53003350-21d47a80-3472-11e9-912d-21743a55a60e.png)

![image](https://user-images.githubusercontent.com/43029852/53003358-24cf6b00-3472-11e9-8a41-cecaa5597ba1.png)

**Comment by enesvtn** [comment]
hey man languages files where ?

**Comment by Ochii** [comment]
Upload your cso2_report_log.txt file (it's inside the Bin folder) and share it here

**Comment by Bridium** [comment]
i solved problem to update new version of master server file
if anybody have this problem update master server
