### ISSUE TITLE
Questions about Nodejs

### ISSUE THREAD

**Issue by wjsrgx** [Ochii/cso2-master-server#50]
When the network is disconnected, start node and cmd cannot display ip.

**Comment by Ochii** [comment]
Send your master server log here

**Comment by wjsrgx** [comment]
![1](https://user-images.githubusercontent.com/18309874/53069657-b80eac00-3517-11e9-963f-85cf2e758fd5.png)

**Comment by Ochii** [comment]
Which command did you type in to start the server?

**Comment by wjsrgx** [comment]
What I entered is "npm run start"

**Comment by organnerx** [comment]
Basic troubleshooting: Check if you downloaded the correct archive from releases. There are 3 files and you need to download archive not called "source code". Also check if node 10 is installed. Try to reinstall it. Don't forget you need 2 commands at the first server launch:
npm install --only=production
npm run start

**Comment by Ochii** [comment]
@wjsrgx did you fix this?
