### ISSUE TITLE
a variety of problems

### ISSUE THREAD

**Issue by DebugBios** [Ochii/cso2-master-server#53]
If you disconnect after connecting to a host room without port forwarding, you will see one person in the room at a certain rate, but two people will be displayed (ghost room).

https://youtu.be/TGd_VAkB_Ag

In addition, any room that is created after disconnection can enter the previous room.
https://youtu.be/6eMMe3wbtO0

If a person enters or leaves repeatedly, the host is reassigned.

**Comment by DebugBios** [comment]
If the team changes from inside the In-game to the second half, it has to change the team in the lobby.

Otherwise, there is no change in the lobby and team assignment may be strange when entering the lobby.

**Comment by DebugBios** [comment]
new client connected 192.168.0.12:2353 uuid: b4f30bd7-83e0-4b32-b8f1-4d498feab7fa
b4f30bd7-83e0-4b32-b8f1-4d498feab7fa sent a version packet. clientHash:
(node:11572) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
user TEST logged in (uuid: b4f30bd7-83e0-4b32-b8f1-4d498feab7fa)

**Comment by Ochii** [comment]
Does [version 0.8.10](https://github.com/Ochii/cso2-master-server/releases/tag/0.8.10) fix this?

**Comment by DebugBios** [comment]
I can't recreate the situation. Maybe it's been fixed.

**Comment by Ochii** [comment]
Ok, I'll close this for now. You can reopen this issue if you recreate the situation again
