### ISSUE TITLE
information question admin panel and commands

### ISSUE THREAD

**Issue by enesvtn** [Ochii/cso2-master-server#58]
Hello @Ochii 

I built the game and did it in English thanks
1- game - weapons - character - I want to remove a few places like the map, but how can I do as a temporary.
2- my game players how to play client did not find server rope binding
3- Normal counter strike 2 is not a fully connected game so if you do not have command systems such as GM banning powers such as events are present and what are the commands.
4- When I install the server, you can help me with installation.
5- In-game purchase feature I have entered into the game I have to give VIP and can buy items available weapons but I have no money to buy how to use this part 
would you help me in writing

**Comment by enesvtn** [comment]
@Ochii  the feature I told you in the next update?

2- When to update the database connection Are you planning

3-in-game purchasing feature available and how do we provide it
Thank you for your reply, you are the perfect developer.<3

**Comment by Ochii** [comment]
I am planning a database implementation, and I haven't looked into the ingame shop

**Comment by enesvtn** [comment]
I believe you will be more on the features you will achieve also the admin panel must have free control right in the game everything is necessary

**Comment by leang97** [comment]
> I believe you will be more on the features you will achieve also the admin panel must have free control right in the game everything is necessary

Right now, at this stage of development, the "Admin privilege" is still not yet necessary(every player is having the same privilege as to access every single item over the server and client-launcher have no hash verification over game files and cheats), it will however need to be implemented as soon as other features have been implemented and developed such as shops, User Accounts controls, etc.

**Comment by enesvtn** [comment]
well how can I make objects such as map in the game - weapons - character temporarily not visible ?you can remove all of these fields from the file you want to remove or remove them temporarily.

**Comment by leang97** [comment]
> well how can I make objects such as map in the game - weapons - character temporarily not visible ?you can remove all of these fields from the file you want to remove or remove them temporarily.

I dont know what you mean but, you can remove a weapon or character from the game by excluding the itemid from the master server to avoid the master server pushing the weapon or character to the client. If you want to remove  game mode, maps, I believe you have to edit the game file's scripts.

**Comment by Ochii** [comment]
> 
> 
> well how can I make objects such as map in the game - weapons - character temporarily not visible ?you can remove all of these fields from the file you want to remove or remove them temporarily.

I set the default equipped items starting here: 

https://github.com/Ochii/cso2-master-server/blob/48ab6bdd1c1b860b6db1df79289a3e0e2169d51d/src/user/userinventory.ts#L21

And I add items to the inventory starting here:

https://github.com/Ochii/cso2-master-server/blob/48ab6bdd1c1b860b6db1df79289a3e0e2169d51d/src/user/userinventory.ts#L53

**Comment by enesvtn** [comment]
Thank you ochii
