### ISSUE TITLE
Design issues

### ISSUE THREAD

**Issue by Ochii** [Ochii/cso2-master-server#59]
## Background

So I have used these last two weeks thinking how to continue developing the master server.

I **have never planned or designed anything** for the master server on paper or in a model, which has impacted it.

As an example, here's a class dependency graph of ServerInstance:

![diapositivo1](https://user-images.githubusercontent.com/4953934/53374785-5011f880-3951-11e9-928b-729c180ff2ce.PNG)

And here's a class dependency graph of UserManager:

![diapositivo2](https://user-images.githubusercontent.com/4953934/53374788-54d6ac80-3951-11e9-9b1a-d2c920b31f31.PNG)

You see it dealing with ChannelManager, ExtendedSocket and in and out packets. (the packets represent **15 imports**)

If you join these two, you get:

![diapositivo3](https://user-images.githubusercontent.com/4953934/53374797-5a33f700-3951-11e9-881f-63a4a7db4b76.PNG)

You can very quickly conclude that this is messy.

If you look at further classes dependencies, you will recognize the same pattern all over.

### (Probably) Nexon's approach

We can use this guessed Nexon approach to come to a solution.

![diapositivo4](https://user-images.githubusercontent.com/4953934/53374807-6455f580-3951-11e9-9444-232e4b262cb8.PNG)

### My proposal

![diapositivo5](https://user-images.githubusercontent.com/4953934/53376470-4fc82c00-3956-11e9-812c-eca9373b8e71.PNG)

I propose a microservices solution, which I believe that it fits the master server's logic.

- The `Client API Gateway` will handle the In and Out packets logic
- The `User Inventory` and `Match Manager` will use MongoDB to store its database data
- I'm unsure about `User Manager` using MongoDB or MySQL
- The asynchronous calls will be implemented through REST, with support of RAML
- There may be more asynchronous events being sent. These will be handled by RabbitMQ
- Consul will be used to handle service discovery and configuration
- It will be deployed through containers

This diagram most likely will change in the future, considering that the master server is in development and there still are unreversed features in the game.

I will try to push this design forward, and write its progress in the repository's project tab.

Feel free to propose any changes.

EDIT: I am not going to abruptly 'microservice-ify' the server. I'll start by creating the databases and chat microservices. I will also keep patching bugs in the current version.

**Comment by enesvtn** [comment]
I want to make suggestions

- Registration must be registered as users should register.
- In-game purchase should be free of charge in the game everything you need to limit the management panel.
- Although the language folder is set, the Korean language is constantly coming.
- The chat should not be active if the system is not working.
-launcher multiplayer for PACTH or exe input must be automatic server ip address is writing very bad image.
- I need an admin.

I'il share it with you. thanks

**Comment by gunslinger23** [comment]
I think they may likely use NoSQL to store the user data 😃

**Comment by leang97** [comment]
> I think they may likely use NoSQL to store the user data

I personally think they were using MySQL. 
Btw, there is an area which I dont understand is that "Public Api Gateway". What is that gateway meant for?

**Comment by enesvtn** [comment]
MySQL. to use the database is more logical and does not want to bother because the other company was using it

**Comment by Ochii** [comment]
> 
> 
> > I think they may likely use NoSQL to store the user data
> 
> I personally think they were using MySQL.
> Btw, there is an area which I dont understand is that "Public Api Gateway". What is that gateway meant for?
> Was it meant for registration of user accounts through other web services, etc?

It's a bridge between the game client and the services. If a game client tries to login, it will send the login info to the gateway. The gateway will then send it over to the user manager service.

When the user manager is done, it will send the reply to the API gateway. Once the gateway receives the reply, it will send it over to the respective client

**Comment by leang97** [comment]
> > > I think they may likely use NoSQL to store the user data
> > 
> > 
> > I personally think they were using MySQL.
> > Btw, there is an area which I dont understand is that "Public Api Gateway". What is that gateway meant for?
> > Was it meant for registration of user accounts through other web services, etc?
> 
> It's a bridge between the game client and the services. If a game client tries to login, it will send the login info to the gateway. The gateway will then send it over to the user manager service.
> 
> When the user manager is done, it will send the reply to the API gateway. Once the gateway receives the reply, it will send it over to the respective client
> 
> EDIT: there is also a public API gateway, which I plan on using it to expose the game's data (such as matches) in a web friendly API. This allows people to create their own apps that access the master server's data

The public api gateway is a very great functionality. We can design a dynamic webpage that can watch player's profile, check for their kds, purchase weapon from web pages and also share their profile to other players. It is a very great idea to have a public api gateway, but there is still many tasks to do before we can go for that approach
