### ISSUE TITLE
Cannot leave results window

### ISSUE THREAD

**Issue by DebugBios** [Ochii/cso2-master-server#64]
If you break into the room after the game, you get an error message.

After that, he can't break into another room and escape from the result screen after the game.

**Comment by dounai2333** [comment]
if you're stuck on the result page, here's a quick and easy way to help you escape:
type- connect 127.0.0.1 -in console
then type disconnect, it will takes you back to the main menu without restart the game (I haven't tried connect 127.0.0.1;disconnect, maybe it works too)

**Comment by DebugBios** [comment]
![cso2_0002](https://user-images.githubusercontent.com/44349391/54276796-8b5b2b00-45d1-11e9-8517-02d3e4437a3e.jpg)
I played zombieZ mode and moved to the results window, but it was impossible to escape by coming to the zombie crush result window that I played before.

**Comment by Ochii** [comment]
> ![cso2_0002](https://user-images.githubusercontent.com/44349391/54276796-8b5b2b00-45d1-11e9-8517-02d3e4437a3e.jpg)
> I played zombieZ mode and moved to the results window, but it was impossible to escape by coming to the zombie crush result window that I played before.

It might be better to open a new issue for this
