### ISSUE TITLE
Lost connection 2004, the second player enters the conference card to load 10%.

### ISSUE THREAD

**Issue by sawada270** [Ochii/cso2-master-server#66]
I set up a server on vps, the first player creates a room, the second player will card 10%, lost connection 2004

**Comment by sawada270** [comment]
how can I solve this situation?

**Comment by devFrostie** [comment]
Room Host should port-forward in his router. set protocol to TCP+UDP and should open 27015 & 27020 port number. then second player can reach to host(first player).
