### ISSUE TITLE
It should be marked as playing in the lobby.

### ISSUE THREAD

**Issue by DebugBios** [Ochii/cso2-master-server#67]
Even though the game is being played, the lobby is marked as "prepared" and there is no telling whether you are entering or not.

**Comment by Ochii** [comment]
Where can I see the mark?

**Comment by DebugBios** [comment]
"CSO2_UI_ROOM_PLAY"		"게임중"

**Comment by Ochii** [comment]
Where does it show? In the room list or in the room lobby?

The room list shows ingame status correctly

**Comment by DebugBios** [comment]
![Inkedcso2_0000_LI](https://user-images.githubusercontent.com/44349391/54484588-3824f900-48ad-11e9-9f4f-d0000343e0cc.jpg)
It shall be marked as" 게임 중" instead of "준비 완료".
