### ISSUE TITLE
When the bot mode is activated, the bot mode symbol does not appear in the room list.

### ISSUE THREAD

**Issue by DebugBios** [Ochii/cso2-master-server#76]
![캡처](https://user-images.githubusercontent.com/44349391/54812375-57b58a80-4cce-11e9-8406-4c42654cdb1e.PNG)
![cso2_0000](https://user-images.githubusercontent.com/44349391/54812386-5edc9880-4cce-11e9-8e18-dda61bd28ced.jpg)

**Comment by Ochii** [comment]
Fixed in 0.8.14
