### ISSUE TITLE
room person limit no longer works after version 0.8.12

### ISSUE THREAD

**Issue by dounai2333** [Ochii/cso2-master-server#87]
everything just like the title, and it works fine until version 0.8.12.
![18)LRF))0TQ_EU74GA5K(}9](https://user-images.githubusercontent.com/45044404/56500351-09014780-653d-11e9-87cd-64aefcadb378.png)

**Comment by DebugBios** [comment]
#85 I think it's the same problem as this issue.

**Comment by leang97** [comment]
Some think of this being a feature. If the system works without crashes, it is fine for me.

**Comment by Ochii** [comment]
Should be fixed in b568cf2
