### ISSUE TITLE
Unable to Build

### ISSUE THREAD

**Issue by Project-Bekrin** [Ochii/cso2-master-server#93]
user@Project:~/dw/cso2/0.9.5$ npm run start

\> cso2-master-server@0.9.5 start /home/user/dw/cso2/0.9.5
\> node dist/server.js

/home/user/dw/cso2/0.9.5/dist/server.js:32
        throw new Error('USERSERVICE_HOST environment variable is not set.');
        ^

Error: USERSERVICE_HOST environment variable is not set.
    at validateEnvVars (/home/user/dw/cso2/0.9.5/dist/server.js:32:15)
    at Timeout.setInterval [as _onTimeout] (/home/user/dw/cso2/0.9.5/dist/server.js:105:5)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

npm ERR! Linux 4.18.0-15-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! cso2-master-server@0.9.5 start: `node dist/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cso2-master-server@0.9.5 start script 'node dist/server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cso2-master-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node dist/server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cso2-master-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cso2-master-server
npm ERR! There is likely additional logging output above.

**Comment by Ochii** [comment]
Sorry, I just fixed the instructions, you can see the [updated README here](https://github.com/Ochii/cso2-master-server#starting-the-master-server).

You need to set the following environment variables:
- `USERSERVICE_HOST` - the host where you're running the user service
- `USERSERVICE_PORT` - the port the user service is listening to
- `INVSERVICE_HOST`  - the host where you're running the user service
- `INVSERVICE_PORT` - the port the inventory service is listening to

You can also read the [instructions in cso2-master-services](https://github.com/Ochii/cso2-master-services#running-the-services) where you can use scripts to download and run everything for you
